#!/bin/bash
#SBATCH --qos pq_jeirinlo
#SBATCH --account=iacc_jeirinlo
#SBATCH --partition IB_44C_512G

# Number of nodes
#SBATCH -N 1

# Number of tasks
#SBATCH -n 16

#SBATCH --output=log_align_test

##########################################################
# Setup envrionmental variable.
##########################################################
export OMP_NUM_THREADS=$SLURM_CPUS_ON_NODE
. $MODULESHOME/../global/profile.modules
module load bismark-0.22.3
pwd; hostname; date

echo "Running program on $SLURM_CPUS_ON_NODE CPU cores"

##########################################################

#bowtie2_dir="/home/applications/bowtie2/2.1.0/bin/"

#samtools_dir="/home/applications/samtools/0.1.19/bin/"

trimmed_files="/scratch/jeirinlo/jrodr979/Clonal_divergence_paper/2020-12-08-WGBS-analysis/Trimmed_reads"

genome="/scratch/jeirinlo/jrodr979/Clonal_divergence_paper/2020-12-08-WGBS-analysis/2020-12-09-Bismark/Bismark_Inputs"


# Alignment -0.2

find ${trimmed_files}/*_R1_001_val_1.fq.gz | xargs basename -s _R1_001_val_1.fq.gz | xargs -I{} bismark \
--path_to_bowtie ${bowtie2_dir} \
--samtools_path ${samtools_dir} \
--non_directional \
-p 8 \
-score_min L,0,-0.2 \
-u 10000 \
--multicore ${SLURM_CPUS_ON_NODE} \
-o /scratch/jeirinlo/jrodr979/Clonal_divergence_paper/2020-12-08-WGBS-analysis/2020-12-09-Bismark/alignment_tests/L,0,-0.2 \
--genome ${genome} \
-1 ${trimmed_files}/{}_R1_001_val_1.fq.gz \
-2 ${trimmed_files}/{}_R2_001_val_2.fq.gz \

# Alignment -0.4

find ${trimmed_files}/*_R1_001_val_1.fq.gz | xargs basename -s _R1_001_val_1.fq.gz | xargs -I{} bismark \
--path_to_bowtie ${bowtie2_dir} \
--samtools_path ${samtools_dir} \
--non_directional \
-p 8 \
-score_min L,0,-0.4 \
-u 10000 \
--multicore ${SLURM_CPUS_ON_NODE} \
-o /scratch/jeirinlo/jrodr979/Clonal_divergence_paper/2020-12-08-WGBS-analysis/2020-12-09-Bismark/alignment_tests/L,0,-0.4 \
--genome ${genome} \
-1 ${trimmed_files}/{}_R1_001_val_1.fq.gz \
-2 ${trimmed_files}/{}_R2_001_val_2.fq.gz \

# Alignment -0.6

find ${trimmed_files}/*_R1_001_val_1.fq.gz | xargs basename -s _R1_001_val_1.fq.gz | xargs -I{} bismark \
--path_to_bowtie ${bowtie2_dir} \
--samtools_path ${samtools_dir} \
--non_directional \
-p 8 \
-score_min L,0,-0.6 \
-u 10000 \
--multicore ${SLURM_CPUS_ON_NODE} \
-o /scratch/jeirinlo/jrodr979/Clonal_divergence_paper/2020-12-08-WGBS-analysis/2020-12-09-Bismark/alignment_tests/L,0,-0.6 \
--genome ${genome} \
-1 ${trimmed_files}/{}_R1_001_val_1.fq.gz \
-2 ${trimmed_files}/{}_R2_001_val_2.fq.gz \

# Alignment -0.9

find ${trimmed_files}/*_R1_001_val_1.fq.gz | xargs basename -s _R1_001_val_1.fq.gz | xargs -I{} bismark \
--path_to_bowtie ${bowtie2_dir} \
--samtools_path ${samtools_dir} \
--non_directional \
-p 8 \
-score_min L,0,-0.9 \
-u 10000 \
--multicore ${SLURM_CPUS_ON_NODE} \
-o /scratch/jeirinlo/jrodr979/Clonal_divergence_paper/2020-12-08-WGBS-analysis/2020-12-09-Bismark/alignment_tests/L,0,-0.9 \
--genome ${genome} \
-1 ${trimmed_files}/{}_R1_001_val_1.fq.gz \
-2 ${trimmed_files}/{}_R2_001_val_2.fq.gz \

# Alignment -1.2

find ${trimmed_files}/*_R1_001_val_1.fq.gz | xargs basename -s _R1_001_val_1.fq.gz | xargs -I{} bismark \
--path_to_bowtie ${bowtie2_dir} \
--samtools_path ${samtools_dir} \
--non_directional \
-p 8 \
-score_min L,0,-1.2 \
-u 10000 \
--multicore ${SLURM_CPUS_ON_NODE} \
-o /scratch/jeirinlo/jrodr979/Clonal_divergence_paper/2020-12-08-WGBS-analysis/2020-12-09-Bismark/alignment_tests/L,0,-1.2 \
--genome ${genome} \
-1 ${trimmed_files}/{}_R1_001_val_1.fq.gz \
-2 ${trimmed_files}/{}_R2_001_val_2.fq.gz \

# Alignment -1.5

find ${trimmed_files}/*_R1_001_val_1.fq.gz | xargs basename -s _R1_001_val_1.fq.gz | xargs -I{} bismark \
--path_to_bowtie ${bowtie2_dir} \
--samtools_path ${samtools_dir} \
--non_directional \
-p 8 \
-score_min L,0,-1.5 \
-u 10000 \
--multicore ${SLURM_CPUS_ON_NODE} \
-o /scratch/jeirinlo/jrodr979/Clonal_divergence_paper/2020-12-08-WGBS-analysis/2020-12-09-Bismark/alignment_tests/L,0,-1.5 \
--genome ${genome} \
-1 ${trimmed_files}/{}_R1_001_val_1.fq.gz \
-2 ${trimmed_files}/{}_R2_001_val_2.fq.gz \

